### ISSUE TITLE
Look into Possible Autonomous Modes

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/BionicFramework#100]
I'd like to look into and breakdown the possible autonomous modes. These should start from the far left/right of the driver station and the center, beside the line near the exchange.

We should have a
- timed auto drive forward (in case encoders break)
- a distance drive forward (in case partners can only switch and our elevator is acting up or something, and prevents us from doing scale)
- either side of switch from center position
- scale auto from far left/right to either scale

These separate modes should be put into an organized list, along with the calculated motion profile points. You can test the points using [Vannaka's MP Generator](https://github.com/vannaka/Motion_Profile_Generator), the actual drivetrain configuration shouldn't matter too much, use the width between the wheels just so you can see how it looks.

The points will then later be injected into our `DriveTrajectory`Command for our auto command groups.

**Comment by ashwinc12** [comment]
Speed = 5 ft/sec
## Baseline
Left (2 sec) `(1.59,23.11)` , `(10, 23.11)` 
Middle (2 sec) `(1.59, 13.1)` , `(10, 13.1)`
Right  (2 sec) `(1.59, 3.9)` , `(10, 3.9)`

## Switch 
Left (2.3 sec) `(1.59, 13.1)` , `(12, 18)`
Right (2.22 sec) `(1.59, 13.1)` , `(12, 9)`

## Left Scale
Left (4.74 sec) `(1.59, 23.11)` , `(25, 19.5)`
Right (6.29 sec) `(1.59, 3.9)` , `(14, 3.9)` , `(25, 19.5)`

## Right Scale
Left (6.29 sec) `(1.59, 23.11)` , `(14, 23.11)`, `(25, 7.5)`
Right (4.74 sec) `(1.59, 3.9)` , `(25, 7.5)`
