### ISSUE TITLE
Research Using Button Board for More Input

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/BionicFramework#12]
For some games, it may be beneficial to have more than the limited number of buttons on the gamepad. Some teams overcome this by using a button board.  A button board simply maps a bunch of physical buttons as another custom joystick.

Here's some documentation on how to use the controller that we have:
[MSP430 LaunchPad Operator Interface for FIRST Robotics Competition](http://processors.wiki.ti.com/index.php/MSP430_LaunchPad_Operator_Interface_for_FIRST_Robotics_Competition)

In the 2018 preseason, we will try to learn more about button boards and possibly create a general button board for future use.

**Comment by roshanr10** [comment]
@TechplexEngineer @jaredbotte is this something we're still considering as an option?

**Comment by TechplexEngineer** [comment]
There is nothing on the to buy list.

**Comment by roshanr10** [comment]
Just wanted to check in if that was something we should add.

I'll close this for the time being, as it seems unlikely with our current schedule.

I'd say these are the ones to use, if we decide to come back to this later:
http://www.leobodnar.com/products/BU0836X/
http://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=94&products_id=205
