### ISSUE TITLE
Joystick Sensitivity Mapping func in BionicJoystick

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/BionicFramework#88]
## Description of Changes Requested
- [ ] Joystick Mapping func in BionicJoystick 

`public double getSensitiveAxis(BionicAxis axis, double deadzone, double sensitivity_coeff)`

https://www.desmos.com/calculator/bhmtf7gvdt

Should be a cubic function using `public double getThresholdAxis`.

## Feature Request Contact (for addt. questions)
@roshanr10

**Comment by jaspercoughlin** [comment]
```
public double getSensitiveAxis(BionicAxis axis, double deadzone, double sensitivity){
		double axisValue = getThresholdAxis(axis, deadzone);

		return (1 - sensitivity) * axisValue + sensitivity * Math.pow(axisValue, 3);
	}
```

**Comment by roshanr10** [comment]
Can you PR this branch in please?
