### ISSUE TITLE
Design Operator Interface

### ISSUE THREAD

**Issue by roshanr10** [FRCteam4909/BionicFramework#99]
Just a matter of tweaking the current `Robot.java` to make the controls more friendly to the driver/operator.

Ask @jaredbotte for more input on how to design the operator interface, and @roshanr10 if you've got additional questions about how to adjust the controls feeding into the subsystem.

EDIT: This should also include determining how we'll be using Shuffleboard (the new dashboard) from cameras and auto choosers to sensor readings.

**Comment by jasonbishop11** [comment]
Controls spreadsheet - https://docs.google.com/spreadsheets/d/12tJWqa2bEwR5QXK4SlrEze-n4QdxQfEQYEtyWJtxAXo/edit?usp=drivesdk

**Comment by roshanr10** [comment]
@jaredbotte what would you like for the dashboard (cameras/sensor readings/manual overrides) ?

**Comment by roshanr10** [comment]
also could we explain more in-depth what climber "semi-auto" is, and why we need a separate cancel?

**Comment by roshanr10** [comment]
I've pushed some changes to the branch `Feature-99` to allow for a toggle for the drivetrain shifter. Please pull updates from GitHub before making further changes.
